{% set version = "9.0.0" %}

package:
  name: openonload
  version: {{ version }}

source:
  url: https://github.com/Xilinx-CNS/onload/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 926b62582df5eb4b38165725e836160fbfe62efa3c055a0e5be0c3e9486717dc

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - libcap
  run:

test:
  commands:
    - test -f $PREFIX/lib/libefcp.so
    - test -d $PREFIX/include/onload
    - test -d $PREFIX/libexec/onload

about:
  home: https://www.xilinx.com/support/download/nic-software-and-drivers.html#open
  summary: 'Onload is a premium add-on product for XtremeScale adapters that provides POSIX compliant TCP, UDP, and multicast interfaces with full kernel bypass.'
  license: GPL-2.0-only AND BSD-2-Clause
  license_file: src/onload/distfiles/LICENSES-ALL

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
